### ISSUE TITLE
PudgeDb is not reliable, need an alternative

### ISSUE THREAD

**Issue by khaledkbadr** [nimscale/stor#5]
I've ran multiple tests and observed the following:
- When I was using `1Mb`, `2Mb` files everything was OK.
- When testing with `3GB` file, data returned from db wasn't able to be uncompressed.
- After that failing rate started to increase dramatically.
- Comparing on uncompressing the real value, and uncompressing the values coming from database showed that problem was from the data coming from the database.

- ERROR: Blocks `~>1mb` had data loss error while storing them. 

Final Test:
- Checking the `md5` of both the input and output of database **did not match in all times**

**Comment by zaibon** [comment]
https://github.com/yinqiwen/ardb has been selected as an alternative
